name: Deploy Angular App to GitHub Pages

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build-and-deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    # Фиксируем одну версию Node.js, без использования matrix
    - name: Use Node.js 24.x
      uses: actions/setup-node@v4
      with:
        node-version: '24.x'
        
    - name: Install dependencies
      run: npm install --no-audit --no-fund
      env:
        CI: true
      
    - name: Run ESLint
      run: npm run lint
      
    - name: Create local environment file
      run: |
        mkdir -p src/environments
        echo "export const environment = { production: true, apiUrl: '', googleClientId: '' };" > src/environments/environment.local.ts
        
    - name: Build Application
      run: npx ng build --configuration production --base-href="/team-42-store/"

    - name: Create 404 page for Angular Routing
      run: cp dist/team-42-store/browser/index.html dist/team-42-store/browser/404.html

    - name: Upload Pages Artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: ./dist/team-42-store/browser

    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4
